name: CI & Deploy Bot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3) Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest


      # 4) Запускаем ваши тесты (если есть pytest/unittest)
      - name: Run tests
        # замените на вашу команду запуска тестов
        continue-on-error: true
        run: |
          pytest --maxfail=1 --disable-warnings -q

      - name: Debug SSH key header
        run: |
          echo "SSH key first line:"
          echo "$SSH_KEY" | head -n1
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}


      # 5) Деплой по SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 46.173.27.175
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /home/velocity_bot
            git pull origin main

            python3 -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

            sudo systemctl restart velocitybot.service
